extends: eslint:recommended

env:
  browser: false     # browser global variables.
  node: true         # Node.js global variables and Node.js-specific rules.
  amd: false         # defines require() and define() as global variables as per the amd spec.
  mocha: true       # adds all of the Mocha testing global variables.
  jasmine: false     # adds all of the Jasmine testing global variables for version 1.3 and 2.0.
  phantomjs: false   # phantomjs global variables.
  jquery: false      # jquery global variables.
  prototypejs: false # prototypejs global variables.
  shelljs: false     # shelljs global variables.
  es6: true

parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    binaryLiterals: false                    # enable binary literals
    blockBindings: false                     # enable let and const (aka block bindings)
    defaultParams: false                     # enable default function parameters
    forOf: false                             # enable for-of loops
    generators: false                        # enable generators
    objectLiteralComputedProperties: false   # enable computed object literal property names
    objectLiteralDuplicateProperties: false  # enable duplicate object literal properties in strict mode
    objectLiteralShorthandMethods: false     # enable object literal shorthand methods
    objectLiteralShorthandProperties: false  # enable object literal shorthand properties
    octalLiterals: false                     # enable octal literals
    regexUFlag: false                        # enable the regular expression u flag
    regexYFlag: false                        # enable the regular expression y flag
    templateStrings: false                   # enable template strings
    unicodeCodePointEscapes: false           # enable code point escapes
    jsx: false                                # enable JSX

rules:
  no-unused-vars: 0
  no-undef: 0
  no-console: 0
  quotes: [1, "single", "avoid-escape"]
  semi: 2
